### ISSUE TITLE
After deletion of mis-classified cells from the image, TSNE plot is not generating

### ISSUE THREAD

**Issue by yuvibim08** [TrigosTeam/SPIAT#10]
Please check for the issue

After running the following script given error is occurred :
script:   
            cell_type_image1 <-  select_celltypes(cell_type_image, c("Cell_3302", "Cell_4917", "Cell_2297", 
                                                                                                                    "Cell_488", "Cell_4362", "Cell_4801", 
                                                                                                                    "Cell_2220", "Cell_3431", "Cell_533", 
                                                                                                                    "Cell_4925", "Cell_4719", "Cell_469", 
                                                                                                                    "Cell_1929", "Cell_310", "Cell_2536", 
                                                                                                                    "Cell_321", "Cell_4195"), 
                                                                                         feature_colname = "rowname", keep = FALSE)

               g_1 <- dimensionality_reduction_plot(cell_type_image1, plot_type = "TSNE", 
                                   feature_colname = "Cell.Type")
Error:   Error in .check_tsne_params(nrow(X), dims = dims, perplexity = perplexity,  : 
            perplexity is too large for the number of samples
![TSNE_plot_error](https://user-images.githubusercontent.com/89310281/184145993-3d5c05f9-10c1-430e-9404-674d1268ae73.png)

**Comment by fuerzhou** [comment]
Hi @yuvibim08,

Thank you very much for raising the issue. Your contribution is important to the tool development.

I suspect that the issue is within our code. I will check our function and get back to you as soon as possible.

Thank you again for your contribution!

**Comment by yuvibim08** [comment]
Thank you for your reply, I will contact you through the mail.

**Comment by fuerzhou** [comment]
The function has been updated in v0.99.2. Now `dimensionality_reduction_plot()` has a new parameter `perplexity`. `perplexity` is adjusted based on the number of samples (cells) in the image. It can also be manually specified.
