### ISSUE TITLE
image_splitter() function is not working

### ISSUE THREAD

**Issue by yuvibim08** [TrigosTeam/SPIAT#12]
Here, I have merged data containing multiple samples. I wanted to split them and work on the split
![image_split_error](https://user-images.githubusercontent.com/89310281/185071704-7c588863-2b51-4c66-bc9e-e3035a39840d.png)
 data. From your tutorial, I tried to do so, but it was not working for me. Please see this issue. Thank you.
Script:
split_image <- image_splitter(M_form_image, number_of_splits=24, plot = FALSE)

Error:
Error in format_colData_to_spe(divided_image) : No data in the dataframe

Script:
split_image <- image_splitter(  M_form_image,
                                number_of_splits=7,
                                plot = FALSE,
                                cut_labels = TRUE,
                                colour_vector = NULL,
                                minX = NULL,
                                maxX = NULL,
                                minY = NULL,
                                maxY = NULL,
                                feature_colname = "Phenotype"
                              )
Error:
Error in format_colData_to_spe(divided_image) : No data in the dataframe

![image_split_error](https://user-images.githubusercontent.com/89310281/185071874-b1830caf-0034-4730-91b6-f0ac003c6ce7.png)

**Comment by fuerzhou** [comment]
Hi @yuvibim08,

Thank you for raising the issue. The issue should have been fixed within the new version v0.99.2. Please reinstall the package and have a go. Please let me know if it fixes the problem.

Thank you!
