### ISSUE TITLE
Encountering error for plot_cell_categories function multiple times 

### ISSUE THREAD

**Issue by yuvibim08** [TrigosTeam/SPIAT#13]
I have encountered an error for function plot_cell_categories multiple times for my data. What will be the reason for this error? Please help me with this.
![plot_cell_categories_error](https://user-images.githubusercontent.com/89310281/186830395-a860f9a2-67f7-47e2-a335-e139139c3756.png)

**Comment by fuerzhou** [comment]
Hi @yuvibim08,

I have fixed the bug in the current v0.99.2 update. Please reinstall the package and try.

Thank you for your contribution!

**Comment by fuerzhou** [comment]
Please let me know if it works.
