### ISSUE TITLE
dimensionality_reduction_plot function not working 

### ISSUE THREAD

**Issue by yuvibim08** [TrigosTeam/SPIAT#14]
After removing misclassified cells from an image using the function select_celltypes, dimensionality_reduction_plot is not generated.
I have tried this function on my data and your example data (simulated image). It is giving errors as 
 
script: g <- dimensionality_reduction_plot(predicted_image2, plot_type = "TSNE", feature_colname = "Cell.Type")

Error : Error in .check_tsne_params(nrow(X), dims = dims, perplexity = perplexity,  : 
  perplexity should be a positive number
In addition: Warning message:
In dimensionality_reduction_plot(predicted_image2, plot_type = "TSNE",  :
  The perplexity for tsne has been changed to -1 due to the small cell count in the image.

I think the perplexity parameter is wrongly defined in the source code. You may need to look into this.

Image of your data
![dimensionality_reduction_plot](https://user-images.githubusercontent.com/89310281/187165113-8f9ff1e5-c732-40eb-8409-2e9f68450cda.png)

Image of my data
![dimensionality_reduction_plot_1](https://user-images.githubusercontent.com/89310281/187166091-310c9d7d-5d1e-41c8-ac6e-274affd150dc.png)

**Comment by fuerzhou** [comment]
Thank you for the update. The issue occurred due to a mistake in the tutorial, where the arg `feature_colname` of function `select_celltype()` should be `Cell.ID` instead of `rowname`. With this mistake, the image after deleting mis-classified cells will contain no cells, resulting in a negative perplexity calculation in `dimensionality_reduction_plot()`. I also updated `dimensionality_reduction_plot()` to return error if there are few cells in the image. 

Please try v0.99.3 and see if it works.

Sorry for the confusion and thank you very much for spotting the issue!

**Comment by yuvibim08** [comment]
> Thank you for the update. The issue occurred due to a mistake in the tutorial, where the arg `feature_colname` of function `select_celltype()` should be `Cell.ID` instead of `rowname`. With this mistake, the image after deleting mis-classified cells will contain no cells, resulting in a negative perplexity calculation in `dimensionality_reduction_plot()`. I also updated `dimensionality_reduction_plot()` to return error if there are few cells in the image.
> 
> Please try v0.99.3 and see if it works.
> 
> Sorry for the confusion and thank you very much for spotting the issue!

I am having an issue with updating the SPIAT version from 0.99.2 to 0.99.3. Following is the error,
![SPIAT_version_update_error](https://user-images.githubusercontent.com/89310281/187359657-ab63a46e-959b-49fc-9fab-0e9c9ee935b8.png)

**Comment by yuvibim08** [comment]
I have followed your instructions and facing another issue, please look into this.

I have tried it for both simulated images and my own data.

Error for my data
![dimensionality_reduction_plot_cell_id_error](https://user-images.githubusercontent.com/89310281/187405255-269d6e4a-0db0-4e79-b396-5def3871e963.png)

Error for simulated image data
![dimensionality_reduction_plot_cell_id_error_SI](https://user-images.githubusercontent.com/89310281/187405267-630413f7-c84e-47a2-a515-672bffcda986.png)

**Comment by fuerzhou** [comment]
You now need to update the package to make it work. Have you tried uninstalling the previous version?

**Comment by yuvibim08** [comment]
Yes, now I have updated the version with the command 'devtools::install_github("TrigosTeam/SPIAT")' and it's working fine for me. SPIAT 0.99.3 is not available on Bioconductor version 3.16. 
Thank you for your help.

![SPIAT_version_update_error1](https://user-images.githubusercontent.com/89310281/187413852-b4ac2a93-9df8-4732-b781-f4bc32833090.png)

**Comment by fuerzhou** [comment]
Yes, it is still under review by Bioconductor. 

I'll close the issue. If there's related problem to this issue in the future, please comment on this closed issue and I'll reopen it. Thank you again for your support!
