### ISSUE TITLE
Encountering errors for analysis related to marker intensity.

### ISSUE THREAD

**Issue by yuvibim08** [TrigosTeam/SPIAT#15]
After deleting misclassified cells from the image using a select_celltypes function, I have tried to use this image for further analysis. but encountering the following errors for marker intensity-related analysis. Please look into it, if I am making any mistakes please let me know. Thank you.

error for average marker intensity:
![avaerage marker intensity](https://user-images.githubusercontent.com/89310281/187861165-80bc93e9-5912-48ac-93fd-64c89fb8611f.png)

Error for stacked surface plot
![stacked surface plot](https://user-images.githubusercontent.com/89310281/187861168-ad20e6b3-ff21-4e92-a7bb-2ea9535027d6.png)

Error for 3D surface plot
![3D surface plot](https://user-images.githubusercontent.com/89310281/187861171-9d290b68-0d7a-427c-9664-36a645f3191b.png)

**Comment by fuerzhou** [comment]
The mistake is from our end and is related to the last update. I have updated the package to 0.99.4 and now the issue should be fixed. 

Thank you again for using the package and for actively contributing to it.

**Comment by yuvibim08** [comment]
Thank you for your assistance, now it's working fine.
