### ISSUE TITLE
AUC_of_cross_function.R AUC can > 1

### ISSUE THREAD

**Issue by Isaacyz** [TrigosTeam/SPIAT#16]
Hi, in current code AUC_of_cross_function.R
The out put AUC can be larger than 1. Is that correct?
Should the line 23 to be **_max(c(df.cross$theo, df.cross$border))_**?
<img width="382" alt="Screen Shot 2022-09-15 at 11 10 25 am" src="https://user-images.githubusercontent.com/95325026/190289923-675cb1eb-f936-454c-8623-45f41ec5db9f.png">

I'm currently analysis one data, which generate K-cross plot like this:
<img width="792" alt="Screen Shot 2022-09-15 at 11 12 56 am" src="https://user-images.githubusercontent.com/95325026/190290194-cf50d74e-e45d-4fb3-b2bf-2c65c47febd8.png">
it returns AUC 2.6.

The current AUC_of_cross_function.R code is to divide blue area to red area.
<img width="804" alt="Screen Shot 2022-09-15 at 11 11 31 am" src="https://user-images.githubusercontent.com/95325026/190290332-e5b11c43-ef03-4c1a-9a28-071c3b148abc.png">

**Comment by fuerzhou** [comment]
Hi @Isaacyz,

Thank you very much for spotting the issue. I think you are right, and we have updated the function in the most recent version v0.99.5. 

Thanks again for your contribution!
