### ISSUE TITLE
Importing annotation and specifying exclusion (negative) markers

### ISSUE THREAD

**Issue by prestigious-bat3868** [TrigosTeam/SPIAT#23]
First of all, this is an amazing package, kudos. I have two questions:

1. Is there any way to import annotations (eg from HALO) to calculate the frequency of cells within manually annotated regions (eg tumour vs non-tumour)? The automatic identification of tumour structure function in SPIAT doesn't work well for my tissue (brain).

If no such way currently exists, do you have any thoughts about a potential workaround?

2. How can I define a negative marker in my phenotype, e.g. "CD4+ PD1-"? I presume "CD4" just means "CD4" regardless of PD1 status.

Thank you in advance!

**Comment by fuerzhou** [comment]
Thanks for your interest in the tool.
1. The package doesn't support importing the annotations directly. A workaround would be manually adding a column to the `colData()` of the `SpatialExperiment` Object. You need to make sure the cell IDs match the corresponding annotations.
2. "CD4" means there is only "CD4" present on the cell without other markers.
Cheers,
Yuzhou

**Comment by prestigious-bat3868** [comment]
Thank you!
