### ISSUE TITLE
Convert spatialExperiment object into Seurat object

### ISSUE THREAD

**Issue by JessicaP94** [TrigosTeam/SPIAT#24]
Firstly, thank you for the amazing package!

I was wondering how I could convert the SpatialExperiment object generated from ``format_image_to_spe`` into a Seurat object. I have data from QuPath but it would be nice to know how to do it also for inForm.

Thank you

**Comment by fuerzhou** [comment]
Thank you for your interest in our tool.
Unfortunately I am not aware of any function to convert SPE objects to Seurat objects. Seurat has the function to read 10x Visium data as Seurat objects but I'm not sure about their functionalities around spatial proteomics data. Perhaps raise the issue with them?

**Comment by RoshanJalal** [comment]
Great package and excited to try it out. Would it be possible to define the phenotype of the cells based on absence of a marker and presence of another as a combination?

Thank you
