### ISSUE TITLE
Question in Quantifying cell colocalisation 

### ISSUE THREAD

**Issue by SGIlabes** [TrigosTeam/SPIAT#31]
Hello, and thank you for developing this remarkable tool for spatial transcriptomics. I have a query regarding its application. I'm working with multiple sets of spatial transcriptomic data, including those from CosMx. My objective is to compare and calculate statistics related to quantifying cell colocalization between two distinct groups. Could you guide me on how to effectively use the Cross K-function or Normalised Mixing Score (NMS) for this analysis?

**Comment by fuerzhou** [comment]
Hi @SGIlabes, 

Thank you for your interest in the tool. If you are interested in getting the metrics for two groups of patients, please refer to the #Challenge section in [this worksheet](https://github.com/TrigosTeam/ABACBS_Workshop_SPIAT_spaSim/blob/main/worksheets/SPIAT_worksheet_solutions.html).
It shows an example of getting the mixing score of two groups of patients and doing survival analysis on them. Please let me know if you have further questions.
