### ISSUE TITLE
How can we get the neighborhood classification for each cells?

### ISSUE THREAD

**Issue by Feng-Zhang** [TrigosTeam/SPIAT#37]
When I run the identify_neighborhoods function to identify neighborhoods:
```
clusters <- identify_neighborhoods(
  image_no_markers, method = "hierarchical", min_neighborhood_size = 100,
  cell_types_of_interest = c("Immune", "Immune1", "Immune2"), radius = 50, 
  feature_colname = "Cell.Type")
```
I can get the image exactly as same as the vignette shows: 
![image1](https://github.com/TrigosTeam/SPIAT/assets/7855694/e7b4821b-2402-4a81-b299-8a9a93561fad)

However, when I try to map the neighborhood back to the tissue, the result is different from the above one. 
![image2](https://github.com/TrigosTeam/SPIAT/assets/7855694/509b7996-b4a6-4b51-bb40-b0fd8c36bbd6)

Does the column "Neighborhood" represent the cluster1,2 and 3 as the vignette shows?

The code I use to plot is here: 
``` 
spatial_coords <- spatialCoords(clusters)
colnames(spatial_coords)[1:2] <- c('x','y')
col_data <- colData(clusters)
df <- data.frame(spatial_coords, col_data)
df %>% ggplot(aes(x = x, y = y)) +
        geom_point(aes(color =Neighborhood)) + 
        theme_bw()
```
Any suggestions would be much appreciated.

**Comment by fuerzhou** [comment]
Hi @Feng-Zhang ,

Thank you very much for pointing this out. There was a mistake in the code that misaligned the spatial coordinates and the clusters ids. And yes, the column "Neighborhood" represents the cluster ids.

I have fixed the code and updated it on Github. The code on Bioconductor will be updated in a couple of days.

Cheers,
Yuzhou
